[package]
name = "octree_voxels"
version = "0.1.0"
edition = "2024"

[dependencies]
block-mesh = "0.2.0"
bytemuck = {version = "1.25.2", features = ["derive"] }
env_logger = "0.11.11"
glam = { version = "0.33.7", features = ["bytemuck", "serde", "fast-math"] }
gltf = "1.4.1"
log = "0.4.34"
ndshape = "0.3.0"
noise = "0.9.0"
pollster = "1.0.1"
rayon = "1.12.0"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
wgpu = "30.0.1"
winit = { version = "0.30.13", features = ["rwh_06"] }
